acta_auditoria/urls.py
from django.urls import path
from . import views

urlpatterns = [
        ]

oficina_calidad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from usuarios_auditoria.views import Login

# Production Packages
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login, name = "login"),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name = "logout"),
    # Local apps
    path('user/', include('usuarios_auditoria.urls')),
    path('programa/',include('programa_auditoria.urls')),
    path('plan/',include('plan_auditoria.urls')),
    path('acta/',include('acta_auditoria.urls')),
    path('informe/',include('informe_auditoria.urls')),
    path('administracion/',include('administracion.urls')),
    path('lista/',include('lista_auditoria.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programa_auditoria/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("add", views.SavePrograma.as_view(), name='add-programa'),
    re_path(r'edit/(?P<data_id>[0-9]+)$',
            views.EditPrograma.as_view(), name='edit-programa'),
    path("view", views.ListPrograma, name="view-programa"),
    path('delete/<int:data_id>', views.DeletePrograma, name='delete-programa'),
    path('viewPdf/<int:data_id>', views.ViewPdfPrograma, name='view-pdf-programa'),
]

programa_auditoria/models.py
from django.db import models
from usuarios_auditoria.models import Auditor
from administracion.models import Proceso, Dependencia
from datetime import datetime

# Create your models here.
class ProgramaAuditoria(models.Model):
    auditor_aprobado = models.ForeignKey(Auditor,null=True,blank=True,on_delete=models.CASCADE,related_name='auditor_aprobado')
    auditor_elaborado = models.ForeignKey(Auditor,null=True,blank=True,on_delete=models.CASCADE,related_name='auditor_elaborado')
    auditor_revisado = models.ForeignKey(Auditor,null=True,blank=True,on_delete=models.CASCADE,related_name='auditor_revisado')
    titulo = models.CharField(max_length=100)
    codigo = models.CharField(max_length=100, default="F-PE01.04-06")
    version = models.CharField(max_length=100, default="2.0")
    objetivo = models.CharField(max_length=100)
    alcance = models.CharField(max_length=100)
    criterios_auditoria = models.CharField(max_length=300, default="")
    modalidad = models.CharField(max_length=50, default="Virtual")
    lugar = models.CharField(max_length=150, default="")
    recursos = models.CharField(max_length=200)
    control_riesgo = models.CharField(max_length=200)
    n_revision = models.IntegerField()
    firma = models.ImageField(upload_to="imagenes/%Y/%m/%d/%H/%M/%S", null=True, blank=True)
    docx_generado = models.BooleanField(default=False)
    fecha_modificacion = models.DateTimeField(default=datetime.now, blank=True)

class ProcesoPrograma(models.Model):
    programa_auditoria = models.ForeignKey(ProgramaAuditoria,null=True,blank=True,on_delete=models.CASCADE)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
  

class ActividadesProcesoPrograma(models.Model):
    proceso_programa = models.ForeignKey(ProcesoPrograma,null=True,blank=True,on_delete=models.CASCADE)
    proceso = models.ForeignKey(Proceso,null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.proceso.nombre

class DependenciasProcesoPrograma(models.Model):
    proceso_programa = models.ForeignKey(ProcesoPrograma,null=True,blank=True,on_delete=models.CASCADE)
    dependencia = models.ForeignKey(Dependencia,null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.dependencia.nombre

#Obtenemos lista de dependencias
#Obtenemos lista de ProcesosPrograma de un Programa
#Iteramos lista de dependencias y en cada iteracion obtenemos lista de dependencias

programa_auditoria/forms.py
from django import forms
from programa_auditoria.models import ProgramaAuditoria
from usuarios_auditoria.models import Auditor
class ProgramaForm(forms.ModelForm):
    class Meta:
        model = ProgramaAuditoria
        fields = ['id', 'auditor_aprobado', 'auditor_elaborado', 'auditor_revisado', 'codigo', 'version', 'objetivo', 'alcance', 'recursos', 'control_riesgo', 'n_revision', 'firma']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['firma'].widget.clear_checkbox_label = 'Quitar firma'
        self.fields['firma'].widget.initial_text = "Imagen actual"
        self.fields['firma'].widget.input_text = "Selecciona una imagen para cambiar la firma"

    id = forms.IntegerField(label='id', required=False)
    auditor_aprobado = forms.ModelChoiceField(required=False, queryset=Auditor.objects.all(), empty_label="Selecciona un auditor")
    auditor_elaborado = forms.ModelChoiceField(queryset=Auditor.objects.all(), empty_label="Selecciona un auditor")
    auditor_revisado = forms.ModelChoiceField(required=False, queryset=Auditor.objects.all(), empty_label="Selecciona un auditor")
    codigo = forms.CharField(label='codigo')
    version = forms.CharField(label='version')
    objetivo = forms.CharField(label='objetivo')
    alcance = forms.CharField(label='alcance')
    recursos = forms.CharField(label='recursos')
    control_riesgo = forms.CharField(label='control_riesgo')
    n_revision = forms.IntegerField(label='n_revision')
    firma = forms.ImageField(label="firma", required=False)

programa_auditoria/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import UpdateView
from programa_auditoria.forms import ProgramaForm
from usuarios_auditoria.models import Auditor, Usuario
from plan_auditoria.models import PlanAuditoria, BloqueProcesoPlan, ProcesoPlanAuditoria, PlanAuditores, PlanFunciones
from programa_auditoria.models import ProgramaAuditoria, ProcesoPrograma,ActividadesProcesoPrograma,DependenciasProcesoPrograma
from administracion.models import Proceso, Dependencia, Facultad, Escuela
from django.http import JsonResponse
from os import remove
import os
from generacion_pdfs.views import crearPdfPrograma, crearPdfPlan, generarPlanesPdfs
from plan_auditoria.views import DeletePlan
from datetime import datetime

# Create your views here.

def ViewPdfPrograma(request, data_id):
    auth_usuario = request.user
    context = {"id": data_id}
    if request.user.is_authenticated:
        usuario = Usuario.objects.get(user=auth_usuario)
        context["user"] = usuario

    return render(request, "programa-view-pdf.html", context)

def DeletePrograma(_request, data_id):
    if not _request.user.is_authenticated:
        return  redirect("login")
    if _request.user.is_authenticated and Usuario.objects.get(user=_request.user).rol != "administrador":
        return  redirect("principal")

    try:
        programa = ProgramaAuditoria.objects.get(id = data_id)
        planes = PlanAuditoria.objects.filter(programa_auditoria = programa)
        for plan in planes:
            DeletePlan(plan)
            plan.delete()

        try:
            rutaDocx = "static/pdfs/programa-" + str(programa.id) + programa.fecha_modificacion.strftime("%Y%m%d%H%M%S") + ".docx"
            remove(rutaDocx)
        except:
            print("Archivo no encontrado")
        programa.delete()
        
        data = {'message': "Success"}
    except:
        data = {'message': "Not Found"}
    return redirect(ListPrograma)

def ListPrograma(request):
    if not request.user.is_authenticated:
        return  redirect("login")
    
    auth_usuario = request.user
    programas = ProgramaAuditoria.objects.all()
    context = {"programas": programas}
    if request.user.is_authenticated:
        usuario = Usuario.objects.get(user=auth_usuario)
        context["user"] = usuario

    return render(request, "programa-table.html", context)

class EditPrograma(View):
   
    #programa = None
    def get(self, request ,*args, **kwargs):
        if not request.user.is_authenticated:
            return  redirect("login")   
        if request.user.is_authenticated and Usuario.objects.get(user=request.user).rol != "administrador":
            return  redirect("principal")
        #print (self.kwargs['data_id'] )

        procesos = Proceso.objects.all()
        dependencias = Dependencia.objects.all()
        auditores = Auditor.objects.filter(estado = True)
        facultades = Facultad.objects.all()
        escuelas = Escuela.objects.all()

        programa = ProgramaAuditoria.objects.get(id=self.kwargs['data_id'])
        #programa = ProgramaAuditoria.objects.filter(codigo="a")
        
        procesos_lista = []
        #print(procesos_lista)

        procesos_programa = ProcesoPrograma.objects.filter(programa_auditoria=programa)
        #print (procesos_programa)
        #procesos_programa  = ProcesoPrograma.get.all(filter (programa_auditoria  = programa ))
        i = 0
        for procesos_unicos in procesos_programa:
            procesos_lista += [[0,0,0,[],[] ]] 
            print (procesos_unicos.fecha_inicio )
            #array [0][0]  = 1
            #array += [[2,3,[],[]]  ]
            procesos_lista[i][0] = procesos_unicos.id 
            procesos_lista[i][1] = procesos_unicos.fecha_inicio 
            procesos_lista[i][2] = procesos_unicos.fecha_fin 
           
            
            actividades = ActividadesProcesoPrograma.objects.filter(proceso_programa=procesos_unicos)
           
            for actividad in actividades:
                procesos_lista[i][3] += [[Proceso.objects.get(id = actividad.proceso.id) , actividad] ]
            
            dependencias_programa = DependenciasProcesoPrograma.objects.filter(proceso_programa=procesos_unicos)
            
            for dependencia_programa in dependencias_programa:
                procesos_lista[i][4] += [[Dependencia.objects.get(id = dependencia_programa.dependencia.id), dependencia_programa]] 
            
            i+=1
            
        #print (procesos_lista)
        planes = PlanAuditoria.objects.filter(programa_auditoria = programa )
        escuelas_antiguo =[]
        facultades_antiguo =[]
        for plan in planes :
            bloques = BloqueProcesoPlan.objects.filter( plan_auditoria = plan)

            for bloque in bloques :
                if bloque.escuela != None:
                    escuelas_antiguo += [bloque.escuela]
                elif bloque.facultad != None:
                     facultades_antiguo += [bloque.facultad]

        print(escuelas_antiguo)
        print(facultades_antiguo)
        
        context = {
            'procesos': procesos,
            'dependencias': dependencias,
            'auditores': auditores,
            'programa': programa,
            'procesos_lista': procesos_lista,
            'facultades': facultades,
            'escuelas': escuelas,
            'facultades_antiguo': facultades_antiguo,
            'escuelas_antiguo': escuelas_antiguo
        }


        if request.user.is_authenticated and Usuario.objects.get(user=request.user).rol == "administrador":
            usuario = Usuario.objects.get(user=request.user)
            context["user"] = usuario
            return render(request, "programa-edit.html", context)
        
        #print(programa)
        #get_context_data or get_object.

        #return render(request, "programa-add.html")

        return redirect(ListPrograma)

    def post(self, request ,*args, **kwargs):
        if not request.user.is_authenticated:
            return  redirect("login")   
        if request.user.is_authenticated and Usuario.objects.get(user=request.user).rol != "administrador":
            return  redirect("principal")

        try:
            #print (self.kwargs['data_id'] )
            if request.method == 'POST':
                #Modificacion inicial de programa
                programa = ProgramaAuditoria.objects.get(id = self.kwargs['data_id'])
                
                antigua_fecha_programa = programa.fecha_modificacion

                procesos_auditoria = int(request.POST.get("n_procesos"))
                antiguos_procesos_auditoria = int(request.POST.get("n_procesos_antiguos"))
                
                antiguo_proceso_id_grupo = request.POST.getlist('antiguo_proceso_id_grupo')
                antiguo_proceso_status_grupo = request.POST.getlist('antiguo_proceso_status_grupo')

                print(antiguo_proceso_status_grupo)

                facultades_ids = request.POST.getlist("facultades_ids")
                escuelas_ids = request.POST.getlist("escuelas_ids")

                planes = PlanAuditoria.objects.filter(programa_auditoria = programa )
                
                for plan in planes :
                    bloques = BloqueProcesoPlan.objects.filter( plan_auditoria = plan)

                    for bloque in bloques :
                        if bloque.escuela != None and not (str(bloque.escuela.id) in escuelas_ids):                     
                            bloque.delete()
                        elif bloque.escuela != None and  (str(bloque.escuela.id) in escuelas_ids): 
                            escuelas_ids.remove(str(bloque.escuela.id))
                        
                        if bloque.facultad != None and not (str(bloque.facultad.id) in facultades_ids):
                            bloque.delete()

                        elif bloque.facultad != None and (str(bloque.facultad.id) in facultades_ids):
                            facultades_ids.remove(str(bloque.facultad.id))

                print ("facultades a crear", facultades_ids)    
                print ("escuelas a crear" , escuelas_ids)    

                diccionario = crearDiccionarioFacEsc(facultades_ids,escuelas_ids)
                    
            
                
                #recorrer planes sin bloques   == 0 , borramos 
                for plan in planes:
                    n_bloques = len(BloqueProcesoPlan.objects.filter( plan_auditoria = plan))
                    print (n_bloques)

                    if n_bloques == 0:
                        plan.delete()
                        
                #programa.setattr(Auditor.objects.get(id=request.POST.get("auditor_aprobado")), 'auditor_aprobado', 'id')
                programa.auditor_aprobado = Auditor.objects.get(id=request.POST.get("auditor_aprobado"))
                programa.auditor_elaborado = Auditor.objects.get(id=request.POST.get("auditor_elaborado"))
                programa.auditor_revisado = Auditor.objects.get(id=request.POST.get("auditor_revisado"))
                programa.titulo = request.POST.get("titulo")
                programa.codigo = request.POST.get("codigo")
                programa.version = request.POST.get("version")
                programa.objetivo = request.POST.get("objetivo")
                programa.alcance = request.POST.get("alcance")
                programa.criterios_auditoria = request.POST.get("criterios_auditoria")
                programa.modalidad = request.POST.get("modalidad")
                programa.lugar = request.POST.get("lugar")
                programa.recursos = request.POST.get("recursos")
                programa.control_riesgo = request.POST.get("control_riesgo")
                programa.n_revision = 1
                programa.fecha_modificacion = datetime.now()

                if request.POST.get("firma-clear_id") == "on":

programa_auditoria/templates/programa-add.html
{% extends 'index.html' %} {% load static %} {% block content %}

<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.css"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"
/>
<!-- partial:index.partial.html -->
<div style="padding-top: 8%; padding-left:16%; padding-right:12%; padding-bottom:1%; background-color: white">
  <form
    action="{% url 'add-programa' %}"
    method="post"
    enctype="multipart/form-data"
    id="formID"
  >
    {% csrf_token %}
    <h4 style="background: #a07b2b; color: white">
      Registro de programa de Auditoria
    </h4>
    <div class="row">
      <div
        class="col-md-3"
        style="height: 102px; padding: 0px; border-style: groove"
        style=""
      >
        <img
          src="{% static 'images/unsa.png' %}"
          style="height: 95%; width: 95%"
        />
      </div>
      <div class="col-md-6" style="padding: 0px">
        <div style="height: 51px; border-style: groove">
          <center><h4>FORMATO</h4></center>
        </div>
        <div style="height: 51px; border-style: groove">
          <center><h4>PROGRAMA DE AUDITORÍA DEL SGC2</h4></center>
        </div>
      </div>
      <div class="col-md-1" style="padding: 0px">
        <div style="height: 34px; border-style: groove">
          <center><h5>CODIGO</h5></center>
        </div>
        <div style="height: 34px; border-style: groove">
          <center><h5>VERSION</h5></center>
        </div>
        <div style="height: 34px; border-style: groove">
          <center><h5>REVISION</h5></center>
        </div>
      </div>
      <div class="col-md-2" style="padding: 0px">
        <div style="height: 34px">
          <textarea
            name="codigo"
            class="form-control"
            rows="3"
            required="required"
            style="resize: none"
            readonly="readonly"
          >
          F-PE01.04-06</textarea
          >
        </div>
        <div style="height: 34px">
          <textarea
            name="version"
            class="form-control"
            rows="1"
            required="required"
            style="resize: none"
            readonly="readonly"
          >
          2.0</textarea
          >
        </div>
        <div style="height: 34px">
          <textarea
            id = "n_revision"
            name="n_revision"
            class="form-control"
            rows="1"
            required="required"
            style="resize: none"
            onKeyUp="validateRevision(event)"
          >
1</textarea
          >
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Titulo</label>
          <textarea
            name="titulo"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>

      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Objetivo</label>
          <textarea
            name="objetivo"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>
      <!--  col-md-6   -->

      <div class="col-md-2">
        <input
          id="submitID"
          type="image"
          src="{% static 'images/guardar.png' %}"
          width="60%"
          class="btn pull-right"
          onclick=""
        />
      </div>
      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Alcance</label>
          <textarea
            name="alcance"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>
      <!--
      <div class="col-md-2">
        <input
          type="image"
          src="{% static 'images/pdf.png' %}"
          width="60%"
          class="btn pull-right"
        />
      </div> -->

      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Criterios de auditoria</label>
          <textarea
            name="criterios_auditoria"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>

      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Modalidad</label>
          <select class="form-control" id="modalidad" name="modalidad">
            <option>Virtual</option>
            <option>Presencial</option>
          </select>
        </div>
      </div>

      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Lugar</label>
          <textarea
            name="lugar"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>

      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Recurso</label>
          <textarea
            name="recursos"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>
      <div class="col-md-10">
        <div class="form-group">
          <label for="first">Control de riesgos</label>
          <textarea
            name="control_riesgo"
            class="form-control"
            rows="1"
            required="required"
          ></textarea>
        </div>
      </div>

      <!--  col-md-6   -->
    </div>

    <button
      type="button"
      class="btn btn-primary btn-sm"
      onclick="CreateTable()"
    >
      <i class="fa fa-plus" aria-hidden="true"></i> Añadir
    </button>
    <button
      type="button"
      class="btn btn-danger btn-sm pull-right"
      onclick="removeProceso()"
    >
      <i class="fa fa-plus" aria-hidden="true"></i> Eliminar
    </button>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" style="width: 35%">Proceso de Auditoria</th>
          <th scope="col" style="width: 30%">Fecha de Auditoria</th>
          <th scope="col" style="width: 35%">Dependencia de Auditoria</th>
        </tr>
      </thead>
      <tbody id="table">
        <tr id="proceso_1">
          <td id="proceso_1_td1">
            <button
              type="button"
              class="btn btn-primary btn-sm"
              style="margin-bottom: 5px"
              onclick="extraSelect('proceso_1_td1',1)"
            >
              Añadir
            </button>
            <button
              type="button"
              class="btn btn-danger btn-sm pull-right"
              onclick="removeActividad('proceso_1_td1',0)"
            >
              <i class="fa fa-plus" aria-hidden="true"></i> Eliminar
            </button>

            <select
              class="form-control select2"
              id="proceso1_1"
              name="proceso_1_procesos"
              style="margin-top: 5px"
            >
              {% for proceso in procesos %}
              <option value="{{proceso.id}}">{{proceso.nombre}}</option>
              {% endfor %}
            </select>
          </td>

          <td id="proceso_1_td2">
            <fieldset class="form-group date-icon">
              <input
                type="date"
                required
                class="col-md-5"
                style="margin-right: 10%; margin-top: 6%; margin-left: 2%"
                id="fecha1_1"
                name="proceso_1_fechas"
                value="{% now "Y-m-d" %}"
              />

              <input
                type="date"
                required
                class="col-md-5"
                style="margin-top: 6%"
                id="fecha1_2"
                name="proceso_1_fechas"
                value="{% now "Y-m-d" %}"
              />
              <br /><br />
            </fieldset>
          </td>

          <td id="proceso_1_td3">
            <!-- <button
              type="button"
              class="btn btn-primary btn-sm"
              style="margin-bottom: 5px"
              onclick="extraSelect2('proceso_1_td3',1)"
            >
              <i class="fa fa-plus" aria-hidden="true"></i> Añadir
            </button> 
            <button
              type="button"
              class="btn btn-danger btn-sm pull-right"
              onclick="removeDependencia('proceso_1_td3',0)"
            >
              <i class="fa fa-plus" aria-hidden="true"></i> Eliminar
            </button> -->
            <select
              class="form-control select2"
              id="dependencia1_1"
              name="proceso_1_dependencias"
            >
              {% for dependencia in dependencias %}
              <option value="{{dependencia.id}}">{{dependencia.nombre}}</option>
              {% endfor %}
            </select>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <br />
          <label>Elaborado por</label>
          <select
            class="form-control select2"
            id="elaborado"
            name="auditor_elaborado"
          >
            {% for auditor in auditores %}
            <option value="{{auditor.id}}">{{auditor}}</option>
            {% endfor %}
          </select>
          <br />
          <label>Revisado por</label>
          <select
            class="form-control select2"
            id="revisado"
            name="auditor_revisado"
          >
            {% for auditor in auditores %}
            <option value="{{auditor.id}}">{{auditor}}</option>
            {% endfor %}
          </select>
          <br />
          <label>Aprobado por</label>
          <select
            class="form-control select2"
            id="aprovado"
            name="auditor_aprobado"
          >
            {% for auditor in auditores %}
            <option value="{{auditor.id}}">{{auditor}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="col-sm-2">
        <label for="id_firma" class="mb-1">Firma: </label>
        <input type="file" name="firma" accept="image/*" id="id_firma" />
        
        <br />
        <br />
        <br />
        
        <div class="multiselect">
          <div class="selectBox" onclick="showCheckboxes('checkboxes1')">
            <select>
              <option>Facultades y Escuelas</option>
            </select>
            <div class="overSelect"></div>
          </div>
          <div class="checkboxes" id="checkboxes1">
            {% for facultad in facultades %}
            <label for="facultad_{{facultad.nombre}}">
              <input
                type="checkbox"
                value="{{facultad.id}}"
                id="facultad_{{facultad.nombre}}"
                name="facultades_ids"
              />{{facultad.nombre}}</label
            >
            {% for escuela in escuelas %} 
            {% if escuela.facultad_id == facultad.id %}
            <label class="escuela" for="escuela_{{escuela.nombre}}">
              <input
                class="escuela"
                type="checkbox"
                value="{{escuela.id}}"
                id="escuela_{{escuela.nombre}}"
                name="escuelas_ids"
              />{{escuela.nombre}}</label
            >
            {% endif %} 
            {% endfor %} 
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <input
      type="number"
      id="n_procesos"
      name="n_procesos"
      value="1"
      style="display: none; margin-bottom: 10px"
    />
  </form>
</div>

<!-- partial -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="{% static 'js/script-programa-add.js' %}"></script>
<script src="{% static 'js/script-entidades-checkboxes.js' %}"></script>
{% endblock %}

programa_auditoria/templates/programa-view-pdf.html
{% extends 'index.html' %} {% load static %} {% block content %}

<div class="container-xl">
  <div class="table-responsive">
    <div class="table-wrapper">
      <div class="table-title">
        <div class="row">
          <div class="col-sm-8">
            <h2 class="Titulo-tabla">Programas de Auditoria<b></b></h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <iframe
    src="{% static 'pdfs/' %}programa-{{id}}.pdf"
    style="width: 100%; height: 700px"
    frameborder="0"
  ></iframe>
  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Roboto"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
  />
  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
  />
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</div>

{% endblock %}